///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace License
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LicenseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("06d52dbb-92a7-4b12-8454-01aa3897f9d4")]
    public partial class LicenseRepository : RepoGenBaseFolder
    {
        static LicenseRepository instance = new LicenseRepository();
        LicenseRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        LicenseRepositoryFolders.AboutSNAPXAppFolder _aboutsnapx;

        /// <summary>
        /// Gets the singleton class instance representing the LicenseRepository element repository.
        /// </summary>
        [RepositoryFolder("06d52dbb-92a7-4b12-8454-01aa3897f9d4")]
        public static LicenseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LicenseRepository() 
            : base("LicenseRepository", "/", null, 0, false, "06d52dbb-92a7-4b12-8454-01aa3897f9d4", ".\\RepositoryImages\\LicenseRepository06d52dbb.rximgres")
        {
            _snapxuntitled = new LicenseRepositoryFolders.SnapXUntitledAppFolder(this);
            _aboutsnapx = new LicenseRepositoryFolders.AboutSNAPXAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("06d52dbb-92a7-4b12-8454-01aa3897f9d4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("e7f216c4-4f15-48b0-8400-975af4e7fa17")]
        public virtual LicenseRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The AboutSNAPX folder.
        /// </summary>
        [RepositoryFolder("3020e450-e53d-4191-b3a2-e3c8625d3fc2")]
        public virtual LicenseRepositoryFolders.AboutSNAPXAppFolder AboutSNAPX
        {
            get { return _aboutsnapx; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class LicenseRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("e7f216c4-4f15-48b0-8400-975af4e7fa17")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _snapxuntitledInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "e7f216c4-4f15-48b0-8400-975af4e7fa17", "")
            {
                _snapxuntitledInfo = new RepoItemInfo(this, "SnapXUntitled", "titlebar[@accessiblerole='TitleBar']", 60000, null, "587e88dd-b9ff-4307-9db2-b6ba96b959f3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e7f216c4-4f15-48b0-8400-975af4e7fa17")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e7f216c4-4f15-48b0-8400-975af4e7fa17")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnapXUntitled item.
            /// </summary>
            [RepositoryItem("587e88dd-b9ff-4307-9db2-b6ba96b959f3")]
            public virtual Ranorex.TitleBar SnapXUntitled
            {
                get
                {
                    return _snapxuntitledInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The SnapXUntitled item info.
            /// </summary>
            [RepositoryItemInfo("587e88dd-b9ff-4307-9db2-b6ba96b959f3")]
            public virtual RepoItemInfo SnapXUntitledInfo
            {
                get
                {
                    return _snapxuntitledInfo;
                }
            }
        }

        /// <summary>
        /// The AboutSNAPXAppFolder folder.
        /// </summary>
        [RepositoryFolder("3020e450-e53d-4191-b3a2-e3c8625d3fc2")]
        public partial class AboutSNAPXAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _helpaboutInfo;

            /// <summary>
            /// Creates a new AboutSNAPX  folder.
            /// </summary>
            public AboutSNAPXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AboutSNAPX", "/form[@title='About SNAP-X']", parentFolder, 30000, null, true, "3020e450-e53d-4191-b3a2-e3c8625d3fc2", "")
            {
                _helpaboutInfo = new RepoItemInfo(this, "HelpAbout", "text[@controlid='1928']", 30000, null, "2456e245-3235-4f42-a1dc-5ca574f49864");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3020e450-e53d-4191-b3a2-e3c8625d3fc2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3020e450-e53d-4191-b3a2-e3c8625d3fc2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HelpAbout item.
            /// </summary>
            [RepositoryItem("2456e245-3235-4f42-a1dc-5ca574f49864")]
            public virtual Ranorex.Text HelpAbout
            {
                get
                {
                    return _helpaboutInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HelpAbout item info.
            /// </summary>
            [RepositoryItemInfo("2456e245-3235-4f42-a1dc-5ca574f49864")]
            public virtual RepoItemInfo HelpAboutInfo
            {
                get
                {
                    return _helpaboutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}